schema:
  format:
    openapi: "3.0.0"
  service_input_type: "HTTPServiceInput"
  pipeline_input_type: "PipelineInputs"

  types:
    HTTPServiceInput:
      type: object
      description: "Input properties for a Lambda backed HTTP API."
      properties:
        lambda_function_name:
          type: string
          description: "The name to be assigned to the Lambda function"
          minLength: 1
          maxLength: 50
          default: "function"
        lambda_handler:
          type: string
          description: "The function within your code that is called to begin execution"
          minLength: 1
          maxLength: 50
          default: "app.handler"
        lambda_runtime:
          type: string
          description: "The runtime for your Lambda service"
          enum: ["nodejs12.x", "python3.8", "ruby2.7", "java11", "go1.x", "dotnetcore3.1"]
          default: "nodejs12.x"
        lambda_s3_bucket:
          type: string
          description: "The s3 bucket for your application code"
          minLength: 1
          maxLength: 200
        lambda_s3_key:
          type: string
          description: "The s3 key for your application code"
          minLength: 1
          maxLength: 200

    PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        pipeline_code_directory:
          type: string
          description: "Source directory for the service"
          default: "lambda-ping-sns"
          minLength: 1
          maxLength: 100
        pipeline_unit_test_command:
          type: string
          description: "The command to run to unit test the application code"
          default: "echo 'add your unit test command here'"
          minLength: 1
          maxLength: 200
        pipeline_packaging_command:
          type: string
          description: "The commands which packages your code into a file called function.zip"
          default: "zip function.zip app.js"
          minLength: 1
          maxLength: 200
        environment_account_ids:
          type: string
          pattern: '^$|^\d{12}(,\d{12})*$'
          description: "The environment account ids for service instances using cross account environment, separated by ,"
          default: ""
          maxLength: 200
